apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: customers
spec:
  clusterName: infinispan
  name: customers
  template: |
    distributedCache:
      mode: "SYNC"
      statistics: "true"
      encoding:
        key:
          mediaType: "application/x-protostream"
        value:
          mediaType: "application/x-protostream"
      persistence:
        tableJdbcStore:
          readOnly: "true"
          shared: "false"
          segmented: "false"
          dialect: "POSTGRES"
          tableName: "customer"
          schema:
            messageName: "Customer"
            package: "db.kineteco"
          connectionPool:
            connectionUrl: "jdbc:postgresql://postgres-sales-service.default:5432/sales"
            driver: "org.postgresql.Driver"
            username: "kineteco"
            password: "kineteco"